# Base de Datos 2025 - EES N°2 "Escuela de Educación Secundaria N°2 Fermín González Ancalao"
### Por Amilcar Jesús Fernández

El proyecto surge como base de entrenamiento, y a su vez, con la necesidad de transformar un paquete aproximado de 250 archivos de extenciones variadas, en su mayoría .doc/docx en una base de datos robusta, consistente y escalable en SQL.
Los archivos pertencen al ciclo lectivo 2025, aunque se observaron archivos de años anteriores. Cada archivo de word contiene normalmente una tabla, aunque existen archivos con varias tablas desconectadas, relacionadas entre sí sólo por contexto.

In [1]:
import pandas as pd
from docx import Document

## 1 - Etapa de **Exploración** inicial de datos

#### División interna de complejidad de archivos
**Los archivos son calificados internamente según su nivel de aporte:**

- Fuente Primaria: **(FP)** Archivos con muchas columnas y datos variados.
- Fuente de Contraste: **(FdC)** Archivos con aportes parciales, datos repetidos de fuentes primarias en varias aportunidades.
- Fuente de Respaldo: **(FdR)** Archivos con tablas simples que sirven para completar faltantes o validar datos.

### 1.1 - Exploración manual de archivo Marzo (FdR)

#### Archivo "1°1° 2025 Marzo" de la carpeta Marzo

Nivel de aporte: **FdR**

Cargo el archivo "1°1° 2025 Marzo" para corroborar que python reconoce la tabla dentro. Tantos filas. columnas como texto.

In [2]:
doc = Document(r"C:\Users\amilc\OneDrive\Proyecto Data Science Media 2\EES Nº 2 2025-20260117T072850Z-3-001\EES Nº 2 2025\Datos 2025\Marzo\1°1° 2025 Marzo.docx")

In [3]:
doc.tables

In [4]:
doc.tables[0]

In [5]:
tabla = doc.tables[0]

In [6]:
tabla

In [7]:
tabla.rows

In [8]:
len(tabla.rows)

29

In [9]:
tabla.rows[0]

In [10]:
tabla.rows[0].cells

(<docx.table._Cell at 0x12deb6d6350>, <docx.table._Cell at 0x12deb6d6a10>)

In [11]:
tabla.rows[0].cells[0].text

'Nº'

In [12]:
tabla.rows[0].cells[1].text

'APELLIDO Y NOMBRES DEL ALUMNO'

In [13]:
len(tabla.rows[0].cells)

2

In [14]:
for celda in tabla.rows[0].cells: 
    print(celda.text)

Nº
APELLIDO Y NOMBRES DEL ALUMNO

In [15]:
for fila in tabla.rows: 
    print(len(fila.cells))

2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2

In [16]:
for fila in tabla.rows: 
    for celda in fila.cells:
        print(celda.text)

Nº
APELLIDO Y NOMBRES DEL ALUMNO

 ACHIGAR, Tiziano

AGUILAR, Ian Nicolás

ALTAMIRANO, Joaquin Román

ARANDA, Maia Mariel

CARRERAS FLAMMINI, Paula Sofía

CEMINO, Tomas Agustín

D`ACHILLI, Juana Antonella

DUHAU, Oriana Marina

ESPINOZA, Gael Mateo

FALASCHI, Oriana Yanil

GIUNTA, Giuliano  Valentino

LACIAR FARFAN, Mateo

MACIAS, Juan

MACIEL, Lourdes

MALDONADO RIGONI, Matías Nicolás

MALDONADO, Giuliano

MARTINEZ, Sofia Isabella a 1º2º 03/04/25

MEDINA, Morena del Carmen

MOSQUEIRA, Lautaro Nahuel

MOSQUEIRA, Nayla Yanet

PACHECO BERTELLI, Santiago

PERONA, Martin Emiliano

SANCHEZ PEÑA, Daiana Jazmín

SANCHEZ PEÑA, Milagros Agostina

UBEDA, Franco Lionel

UÑATE, Thiago Santino

ZACARIAS, Kevin Alejandro

ZERPA, Fernando Damián

#### La columna N° estaba enumerada mediante numeración automática en word, por tanto no se imprimió como texto, debido a que el texto es inexistente

In [17]:
alumnos = []
for fila in tabla.rows[1:]:
    nombre = fila.cells[1].text
    alumnos.append(nombre)

In [18]:
alumnos

[' ACHIGAR, Tiziano',
 'AGUILAR, Ian Nicolás',
 'ALTAMIRANO, Joaquin Román',
 'ARANDA, Maia Mariel',
 'CARRERAS FLAMMINI, Paula Sofía',
 'CEMINO, Tomas Agustín',
 'D`ACHILLI, Juana Antonella',
 'DUHAU, Oriana Marina',
 'ESPINOZA, Gael Mateo',
 'FALASCHI, Oriana Yanil',
 'GIUNTA, Giuliano  Valentino',
 'LACIAR FARFAN, Mateo',
 'MACIAS, Juan',
 'MACIEL, Lourdes',
 'MALDONADO RIGONI, Matías Nicolás',
 'MALDONADO, Giuliano',
 'MARTINEZ, Sofia Isabella a 1º2º 03/04/25',
 'MEDINA, Morena del Carmen',
 'MOSQUEIRA, Lautaro Nahuel',
 'MOSQUEIRA, Nayla Yanet',
 'PACHECO BERTELLI, Santiago',
 'PERONA, Martin Emiliano',
 'SANCHEZ PEÑA, Daiana Jazmín',
 'SANCHEZ PEÑA, Milagros Agostina',
 'UBEDA, Franco Lionel',
 'UÑATE, Thiago Santino',
 'ZACARIAS, Kevin Alejandro',
 'ZERPA, Fernando Damián']

###### Se utiliza el estandar: 'APELLIDO, Nombre'

In [19]:
alumnos_sospechosos = []

for alumno in alumnos:
    if any(caracter.isdigit() for caracter in alumno) or "°" in alumno or "/" in alumno or alumno != alumno.strip():
        alumnos_sospechosos.append(alumno)

alumnos_sospechosos

[' ACHIGAR, Tiziano', 'MARTINEZ, Sofia Isabella a 1º2º 03/04/25']

In [20]:
cont = 0 

for alumno in alumnos:
    if alumno != alumno.strip():
        cont += 1
cont

1

In [21]:
for caracter in "MARTINEZ, Sofia Isabella a 1º2º 03/04/25": 
    print(caracter,ord(caracter))

M 77
A 65
R 82
T 84
I 73
N 78
E 69
Z 90
, 44
  32
S 83
o 111
f 102
i 105
a 97
  32
I 73
s 115
a 97
b 98
e 101
l 108
l 108
a 97
  32
a 97
  32
1 49
º 186
2 50
º 186
  32
0 48
3 51
/ 47
0 48
4 52
/ 47
2 50
5 53

#### Limpieza del contenido de alumnos en una nueva variable
Sólo se quitaron espacios, se conserva el dato sucio 'MARTINEZ, Sofia Isabella a 1º2º 03/04/25', como base de observación

In [22]:
alumnos_limpios = []

for alumno in alumnos:
    alumno_limpio = alumno.strip()
    alumnos_limpios.append(alumno_limpio)
alumnos_limpios

['ACHIGAR, Tiziano',
 'AGUILAR, Ian Nicolás',
 'ALTAMIRANO, Joaquin Román',
 'ARANDA, Maia Mariel',
 'CARRERAS FLAMMINI, Paula Sofía',
 'CEMINO, Tomas Agustín',
 'D`ACHILLI, Juana Antonella',
 'DUHAU, Oriana Marina',
 'ESPINOZA, Gael Mateo',
 'FALASCHI, Oriana Yanil',
 'GIUNTA, Giuliano  Valentino',
 'LACIAR FARFAN, Mateo',
 'MACIAS, Juan',
 'MACIEL, Lourdes',
 'MALDONADO RIGONI, Matías Nicolás',
 'MALDONADO, Giuliano',
 'MARTINEZ, Sofia Isabella a 1º2º 03/04/25',
 'MEDINA, Morena del Carmen',
 'MOSQUEIRA, Lautaro Nahuel',
 'MOSQUEIRA, Nayla Yanet',
 'PACHECO BERTELLI, Santiago',
 'PERONA, Martin Emiliano',
 'SANCHEZ PEÑA, Daiana Jazmín',
 'SANCHEZ PEÑA, Milagros Agostina',
 'UBEDA, Franco Lionel',
 'UÑATE, Thiago Santino',
 'ZACARIAS, Kevin Alejandro',
 'ZERPA, Fernando Damián']

In [23]:
for original, limpio in zip(alumnos, alumnos_limpios): 
    if original != limpio:
        print("ORIGINAL:", original)
        print("LIMPIO:", limpio)

ORIGINAL:  ACHIGAR, Tiziano
LIMPIO: ACHIGAR, Tiziano

##### Creación de listas y desfragmentación del nombre del alumno
Se separa "APELLIDO, Nombre" de " metadatos" y se guardan ambos en dos listas por separado, una lista para incorporarse a la nueva sección de alumnos
corregida, y la otra como observación para futuros casos.

In [24]:
alumnos_corregidos = []
observaciones_marzo = []

for alumno in alumnos_limpios:
    if " a " in alumno and any(caracter.isdigit() for caracter in alumno):
        partes = alumno.split(" a", 1)
        nombre_limpio = partes[0]
        observacion = "a " + partes[1]
    else: 
        nombre_limpio = alumno
        observacion = None
    alumnos_corregidos.append(nombre_limpio)
    observaciones_marzo.append(observacion)

In [25]:
for nombre, obs in zip(alumnos_corregidos,observaciones_marzo): ## Comprobación de funcionamiento de la desfragmentación del nombre
    if obs is not None:
        print("NOMBRE:", nombre)
        print("OBS:", obs)

NOMBRE: MARTINEZ, Sofia Isabella
OBS: a  1º2º 03/04/25

In [26]:
alumnos_corregidos

['ACHIGAR, Tiziano',
 'AGUILAR, Ian Nicolás',
 'ALTAMIRANO, Joaquin Román',
 'ARANDA, Maia Mariel',
 'CARRERAS FLAMMINI, Paula Sofía',
 'CEMINO, Tomas Agustín',
 'D`ACHILLI, Juana Antonella',
 'DUHAU, Oriana Marina',
 'ESPINOZA, Gael Mateo',
 'FALASCHI, Oriana Yanil',
 'GIUNTA, Giuliano  Valentino',
 'LACIAR FARFAN, Mateo',
 'MACIAS, Juan',
 'MACIEL, Lourdes',
 'MALDONADO RIGONI, Matías Nicolás',
 'MALDONADO, Giuliano',
 'MARTINEZ, Sofia Isabella',
 'MEDINA, Morena del Carmen',
 'MOSQUEIRA, Lautaro Nahuel',
 'MOSQUEIRA, Nayla Yanet',
 'PACHECO BERTELLI, Santiago',
 'PERONA, Martin Emiliano',
 'SANCHEZ PEÑA, Daiana Jazmín',
 'SANCHEZ PEÑA, Milagros Agostina',
 'UBEDA, Franco Lionel',
 'UÑATE, Thiago Santino',
 'ZACARIAS, Kevin Alejandro',
 'ZERPA, Fernando Damián']

#### Creación del dataframe para la fuente Marzo

In [27]:
df_marzo = pd.DataFrame({
    "nombre_completo":alumnos_corregidos,
    "observacion_marzo":observaciones_marzo,
    "curso":"1",
    "division":"1",
    "anio":"2025",
    "fuente":"Marzo",
    "archivo_origen":"1°1° 2025 Marzo.docx"
})

In [28]:
df_marzo.head()

,nombre_completo,observacion_marzo,curso,division,anio,fuente,archivo_origen
0,"ACHIGAR, Tiziano",NaN,1,1,2025,Marzo,1°1° 2025 Marzo.docx
1,"AGUILAR, Ian Nicolás",NaN,1,1,2025,Marzo,1°1° 2025 Marzo.docx
2,"ALTAMIRANO, Joaquin Román",NaN,1,1,2025,Marzo,1°1° 2025 Marzo.docx
3,"ARANDA, Maia Mariel",NaN,1,1,2025,Marzo,1°1° 2025 Marzo.docx
4,"CARRERAS FLAMMINI, Paula Sofía",NaN,1,1,2025,Marzo,1°1° 2025 Marzo.docx

### 1.2 - Exploración manual de archivo Datos (FP)

#### Archivo "1°1° 2025 Datos" de la carpeta Datos

Nivel de aporte: **FP**

Cargo el archivo "1°1° 2025 Datos" para corroborar que python reconoce la tabla dentro. Tantos filas. columnas como texto.

In [29]:
doc = Document(r"C:\Users\amilc\OneDrive\Proyecto Data Science Media 2\EES Nº 2 2025-20260117T072850Z-3-001\EES Nº 2 2025\Datos 2025\Datos\1°1° 2025 Datos.docx")

In [30]:
doc.tables

In [31]:
len(doc.tables)

1

In [32]:
doc.tables[0]

In [33]:
tabla1 = doc.tables[0]

In [34]:
tabla1

In [35]:
tabla1.rows

In [36]:
len(tabla1.rows)

28

#### Inconsistencia detectada
Primera posible inconsistencia detectada. Este archivo contiene datos de alumnos del curso 1° división 1°. El mismo es una fuente primaria que se
equivale directamente con el archivo anterior. Es decir, si 1°1° 2025 Marzo tiene 29 filas (28 alumnos + encabezado), 1°1° 2025 Datos debería 
seguir la misma lógica y sólo variar en la cantidad de columnas.

In [37]:
tabla1.rows[0]

In [38]:
tabla1.rows[0].cells

(<docx.table._Cell at 0x12deb716350>,
 <docx.table._Cell at 0x12deb6e2010>,
 <docx.table._Cell at 0x12deb714bd0>,
 <docx.table._Cell at 0x12deb701150>,
 <docx.table._Cell at 0x12deb718c90>,
 <docx.table._Cell at 0x12deb7188d0>,
 <docx.table._Cell at 0x12deb718b90>,
 <docx.table._Cell at 0x12deb718b50>,
 <docx.table._Cell at 0x12deb7180d0>,
 <docx.table._Cell at 0x12deb718a50>,
 <docx.table._Cell at 0x12deb7186d0>,
 <docx.table._Cell at 0x12deb718e10>)

In [39]:
len(tabla1.rows[0].cells)

12

In [40]:
tabla1.rows[0].cells[1].text

'APELLIDO Y NOMBRES DEL ALUMNO'

In [41]:
for celda in tabla1.rows[0].cells:
    print (celda.text)

Nº
APELLIDO Y NOMBRES DEL ALUMNO
LM
F
Leg
ESC
D.N.I.
F.N.
Lugar
E
Dirección
Teléfono

In [42]:
for fila in tabla1.rows[1:]: 
    for celda in fila.cells:
        print(celda.text)

 ACHIGAR, Tiziano
42
240
31/25
25
52746170
26/12/12
Punta Alta
12
Humberto 2538
2932-520752M

AGUILAR, Ian Nicolás
42
241
32/25
4
52778569
27/11/12
Punta Alta
12
Bº Albatros XXVII c393
2932-573441M

ALTAMIRANO, Joaquin Román
42
242
33/25
8
52887715
14/01/13
San Juan
12
Humberto 1916
2932-614538M

ARANDA, Maia Mariel
42
243
34/25
1
52617713
06/07/12
Punta Alta
12
Entre Ríos 1899
2932-520048P

CARRERAS FLAMMINI, Paula Sofía
42
244
35/25
8
52961006
01/02/13
Juris Fed
12
Humberto 2447
2932-505154M

CEMINO, Tomas Agustín
42
245
36/25
25
52841626
05/01/13
Punta Alta
12
Colón 3579
2932-410841M

D`ACHILLI, Juana Antonella
42
246
37/25
8
52961083
09/04/13
Juris Fed
12
Bº Albatros XXVII c259
2932474863/441518M

DUHAU, Oriana Marina
42
247
38/25
8
52961107
02/05/13
Juris Fed
12
Pringles 199
2932-404188M

ESPINOZA, Gael Mateo
42
248
39/25
25
52746153
08/01/13
Juris Fed
12
Bº Albatros XIV c170
2932-447160/441779M

FALASCHI, Oriana Yanil
42
249
40/25
9
52746139
11/12/12
Juris Fed
12
Río Pilcomayo 288
2932-635639M

GIUNTA, Giuliano  Valentino
42
250
41/25
15
52590347
15/06/12
Punta Alta
13
Sarmiento 520 VdM
2932-479460P

LACIAR FARFAN, Mateo
43
1
42/25
25
52746080
24/10/12
Juris Fed
12
Bº Albatros XIV c213
2932-554870M

MACIAS, Juan
43
2
43/25
9
52746089
06/11/12
Juris Fed
12
Bº Empl. de Comercio c79
2932-465778

MACIEL, Lourdes
43
3
44/25
8
52961168
31/05/13
Juris Fed
12
Bº Centenario 458
2932-515446M

MALDONADO RIGONI, Matías Nicolás
43
4
45/25
8
52943554
05/03/13
Misiones
12
Bº Albatros XV c136
011-57524111M

MALDONADO, Giuliano
43
5
46/25
23
53129727
27/05/13
Azul
12
Humberto 2476
2281-571428M

MEDINA, Morena del Carmen
43
7
48/25
25
52746128
11/12/12
Juris Fed
12
Río Bermejo 839
2932-5026617416120P

MOSQUEIRA, Lautaro Nahuel
43
8
49/25
16
52778589
21/11/12
Punta Alta
12
Río Uruguay 273
2932-503649M

MOSQUEIRA, Nayla Yanet
43
9
50/25
16
52778588
21/11/12
Punta Alta
12
Río Uruguay 273
2932-503649M

PACHECO BERTELLI, Santiago
43
10
51/25
8
52746123
08/12/12
Juris Fed
12
Pellegrini 823 Dto 1
2932-639746P

PERONA, Martin Emiliano
43
11
52/25
7
53209680
12/06/13
Punta Alta
12
El Salvador 724 VA
2932-522015M

SANCHEZ PEÑA, Daiana Jazmín
43
12
53/25
1
52746040
03/10/12
Juris Fed
12
Bº Albatros XXVII c160
2932-573334M

SANCHEZ PEÑA, Milagros Agostina
43
13
54/25
1
50467337
22/04/11
Juris Fed
14
Bº Albatros XXVII c160
2932-573334M

UBEDA, Franco Lionel
43
14
55/25
25
48345434
11/07/10
Juris Fed
14
Humberto 3655
2932-509256M

UÑATE, Thiago Santino
43
15
56/25
25
52961001
04/02/13
Juris Fed
12
Buchardo 3266
2932-631139M

ZACARIAS, Kevin Alejandro
43
16
57/25
4
52617707
26/07/12
Punta Alta
12
17 de febrero 1794
2932-457126M

ZERPA, Fernando Damián
43
17
58/25
16
52710252
13/09/12
Bs As
12
Río Colorado 210
2932-476473P

#### Limpieza de datos

#### Creación del diccionario "registros_datos"

In [43]:
registros_datos = []

for fila in tabla1.rows[1:]:
    telefono_original = fila.cells[11].text
    telefono_num = "".join(caracter for caracter in telefono_original if caracter.isdigit())
    tipo_contacto = telefono_original[-1] if telefono_original[-1].isalpha() else None
    
    registro = {
        "nombre_completo":fila.cells[1].text.strip(),
        "curso":"1",
        "division":"1",
        "anio":"2025",
        "libro_matriz":fila.cells[2].text,
        "folio":fila.cells[3].text,
        "legajo":fila.cells[4].text,
        "esc_proced":fila.cells[5].text,
        "dni":fila.cells[6].text,
        "fecha_nac":fila.cells[7].text,
        "lugar_nac":fila.cells[8].text,
        "edad":fila.cells[9].text,
        "dirección":fila.cells[10].text,
        "telefono_original":telefono_original,
        "telefono_num":telefono_num,
        "tipo_contacto":tipo_contacto,
        "fuente":"Datos",
        "archivo_origen":"1°1° 2025 Datos.docx"
    }
    registros_datos.append(registro)

In [44]:
len(registros_datos)

27

In [45]:
registros_datos[0]

{'nombre_completo': 'ACHIGAR, Tiziano',
 'curso': '1',
 'division': '1',
 'anio': '2025',
 'libro_matriz': '42',
 'folio': '240',
 'legajo': '31/25',
 'esc_proced': '25',
 'dni': '52746170',
 'fecha_nac': '26/12/12',
 'lugar_nac': 'Punta Alta',
 'edad': '12',
 'dirección': 'Humberto 2538',
 'telefono_original': '2932-520752M',
 'telefono_num': '2932520752',
 'tipo_contacto': 'M',
 'fuente': 'Datos',
 'archivo_origen': '1°1° 2025 Datos.docx'}

#### Creación del dataframe para la fuente Datos

In [46]:
df_datos = pd.DataFrame(registros_datos)

In [47]:
df_datos.head()

,nombre_completo,curso,division,anio,libro_matriz,folio,legajo,esc_proced,dni,fecha_nac,lugar_nac,edad,dirección,telefono_original,telefono_num,tipo_contacto,fuente,archivo_origen
0,"ACHIGAR, Tiziano",1,1,2025,42,240,31/25,25,52746170,26/12/12,Punta Alta,12,Humberto 2538,2932-520752M,2932520752,M,Datos,1°1° 2025 Datos.docx
1,"AGUILAR, Ian Nicolás",1,1,2025,42,241,32/25,4,52778569,27/11/12,Punta Alta,12,Bº Albatros XXVII c393,2932-573441M,2932573441,M,Datos,1°1° 2025 Datos.docx
2,"ALTAMIRANO, Joaquin Román",1,1,2025,42,242,33/25,8,52887715,14/01/13,San Juan,12,Humberto 1916,2932-614538M,2932614538,M,Datos,1°1° 2025 Datos.docx
3,"ARANDA, Maia Mariel",1,1,2025,42,243,34/25,1,52617713,06/07/12,Punta Alta,12,Entre Ríos 1899,2932-520048P,2932520048,P,Datos,1°1° 2025 Datos.docx
4,"CARRERAS FLAMMINI, Paula Sofía",1,1,2025,42,244,35/25,8,52961006,01/02/13,Juris Fed,12,Humberto 2447,2932-505154M,2932505154,M,Datos,1°1° 2025 Datos.docx

#### Búsqueda de inconsistencia
Creo dos variables para comparar en que archivo falta un alumno y muestro en cual

In [48]:
faltan_en_datos = set(alumnos) - set(df_datos["nombre_completo"])

In [49]:
faltan_en_marzo = set(df_datos["nombre_completo"]) - set(alumnos)

In [50]:
faltan_en_datos

{' ACHIGAR, Tiziano', 'MARTINEZ, Sofia Isabella a 1º2º 03/04/25'}

In [51]:
faltan_en_marzo

{'ACHIGAR, Tiziano'}

### 1.3 - Exploración manual de archivo Legajos (FdC)

#### Archivo "1°1° 2025 Legajos" de la carpeta Legajos

Nivel de aporte: **FdC**

Cargo el archivo "1°1° 2025 Legajos" para corroborar que python lo lee igual que al anterior

In [52]:
doc = Document(r"C:\Users\amilc\OneDrive\Proyecto Data Science Media 2\EES Nº 2 2025-20260117T072850Z-3-001\EES Nº 2 2025\Datos 2025\Legajos\1°1° 2025 Legajos.docx")

In [53]:
doc.tables

In [54]:
len(doc.tables)

1

In [55]:
tabla2 = doc.tables[0]

In [56]:
tabla2

In [57]:
tabla2.rows

In [58]:
len(tabla2.rows)

28

##### Insight detectado
El archivo de legajos cuenta con 27 registros de alumnos más uno de encabezados. Por lo que se alinea con datos y no así con marzo. Se sospecha la no
inclución de la alumna MARTINEZ, Sofía Isabella, quien tiene fecha de incorporación en abril de 2025.

In [59]:
tabla2.rows[0].cells

(<docx.table._Cell at 0x12deb74bdd0>,
 <docx.table._Cell at 0x12deb766a10>,
 <docx.table._Cell at 0x12deb766110>,
 <docx.table._Cell at 0x12deb7661d0>,
 <docx.table._Cell at 0x12deb7674d0>)

In [60]:
tabla2.rows[0].cells[0].text

'Nº'

In [61]:
tabla2.rows[0].cells[1].text

'APELLIDO Y NOMBRES DEL ALUMNO'

In [62]:
for celda in tabla2.rows[0].cells:
    print(celda.text)

Nº
APELLIDO Y NOMBRES DEL ALUMNO
LM
F
Leg

In [63]:
for fila in tabla2.rows[1:]: 
    for celda in fila.cells:
        print(celda.text)

 ACHIGAR, Tiziano
42
240
31/25

AGUILAR, Ian Nicolás
42
241
32/25

ALTAMIRANO, Joaquin Román
42
242
33/25

ARANDA, Maia Mariel
42
243
34/25

CARRERAS FLAMMINI, Paula Sofía
42
244
35/25

CEMINO, Tomas Agustín
42
245
36/25

D`ACHILLI, Juana Antonella
42
246
37/25

DUHAU, Oriana Marina
42
247
38/25

ESPINOZA, Gael Mateo
42
248
39/25

FALASCHI, Oriana Yanil
42
249
40/25

GIUNTA, Giuliano  Valentino
42
250
41/25

LACIAR FARFAN, Mateo
43
1
42/25

MACIAS, Juan
43
2
43/25

MACIEL, Lourdes
43
3
44/25

MALDONADO RIGONI, Matías Nicolás
43
4
45/25

MALDONADO, Giuliano
43
5
46/25

MEDINA, Morena del Carmen
43
7
48/25

MOSQUEIRA, Lautaro Nahuel
43
8
49/25

MOSQUEIRA, Nayla Yanet
43
9
50/25

PACHECO BERTELLI, Santiago
43
10
51/25

PERONA, Martin Emiliano
43
11
52/25

SANCHEZ PEÑA, Daiana Jazmín
43
12
53/25

SANCHEZ PEÑA, Milagros Agostina
43
13
54/25

UBEDA, Franco Lionel
43
14
55/25

UÑATE, Thiago Santino
43
15
56/25

ZACARIAS, Kevin Alejandro
43
16
57/25

ZERPA, Fernando Damián
43
17
58/25

#### Creación del diccionario registros_legajos

In [64]:
registros_legajos = []

for fila in tabla2.rows[1:]:
    registro_leg = {
        "nombre_completo":fila.cells[1].text.strip(),
        "curso":"1",
        "division":"1",
        "anio":"2025",
        "libro_matriz":fila.cells[2].text,
        "folio":fila.cells[3].text,
        "legajo":fila.cells[4].text,
        "fuente":"Legajos",
        "archivo_origen":"1°1° 2025 Legajos.docx"
    }
    registros_legajos.append(registro_leg)

registros_legajos

[{'nombre_completo': 'ACHIGAR, Tiziano',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '42',
  'folio': '240',
  'legajo': '31/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'AGUILAR, Ian Nicolás',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '42',
  'folio': '241',
  'legajo': '32/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'ALTAMIRANO, Joaquin Román',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '42',
  'folio': '242',
  'legajo': '33/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'ARANDA, Maia Mariel',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '42',
  'folio': '243',
  'legajo': '34/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'CARRERAS FLAMMINI, Paula Sofía',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '42',
  'folio': '244',
  'legajo': '35/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'CEMINO, Tomas Agustín',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '42',
  'folio': '245',
  'legajo': '36/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'D`ACHILLI, Juana Antonella',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '42',
  'folio': '246',
  'legajo': '37/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'DUHAU, Oriana Marina',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '42',
  'folio': '247',
  'legajo': '38/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'ESPINOZA, Gael Mateo',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '42',
  'folio': '248',
  'legajo': '39/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'FALASCHI, Oriana Yanil',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '42',
  'folio': '249',
  'legajo': '40/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'GIUNTA, Giuliano  Valentino',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '42',
  'folio': '250',
  'legajo': '41/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'LACIAR FARFAN, Mateo',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '43',
  'folio': '1',
  'legajo': '42/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'MACIAS, Juan',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '43',
  'folio': '2',
  'legajo': '43/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'MACIEL, Lourdes',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '43',
  'folio': '3',
  'legajo': '44/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'MALDONADO RIGONI, Matías Nicolás',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '43',
  'folio': '4',
  'legajo': '45/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'MALDONADO, Giuliano',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '43',
  'folio': '5',
  'legajo': '46/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'MEDINA, Morena del Carmen',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '43',
  'folio': '7',
  'legajo': '48/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'MOSQUEIRA, Lautaro Nahuel',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '43',
  'folio': '8',
  'legajo': '49/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'MOSQUEIRA, Nayla Yanet',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '43',
  'folio': '9',
  'legajo': '50/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'PACHECO BERTELLI, Santiago',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '43',
  'folio': '10',
  'legajo': '51/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'PERONA, Martin Emiliano',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '43',
  'folio': '11',
  'legajo': '52/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'SANCHEZ PEÑA, Daiana Jazmín',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '43',
  'folio': '12',
  'legajo': '53/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'SANCHEZ PEÑA, Milagros Agostina',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '43',
  'folio': '13',
  'legajo': '54/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'UBEDA, Franco Lionel',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '43',
  'folio': '14',
  'legajo': '55/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'UÑATE, Thiago Santino',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '43',
  'folio': '15',
  'legajo': '56/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'ZACARIAS, Kevin Alejandro',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '43',
  'folio': '16',
  'legajo': '57/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'},
 {'nombre_completo': 'ZERPA, Fernando Damián',
  'curso': '1',
  'division': '1',
  'anio': '2025',
  'libro_matriz': '43',
  'folio': '17',
  'legajo': '58/25',
  'fuente': 'Legajos',
  'archivo_origen': '1°1° 2025 Legajos.docx'}]

In [65]:
len(registros_legajos)

27

In [66]:
registros_legajos[0]

{'nombre_completo': 'ACHIGAR, Tiziano',
 'curso': '1',
 'division': '1',
 'anio': '2025',
 'libro_matriz': '42',
 'folio': '240',
 'legajo': '31/25',
 'fuente': 'Legajos',
 'archivo_origen': '1°1° 2025 Legajos.docx'}

#### Creación del dataframe para la fuente Legajos

In [67]:
df_legajos = pd.DataFrame(registros_legajos)

df_legajos.head()

,nombre_completo,curso,division,anio,libro_matriz,folio,legajo,fuente,archivo_origen
0,"ACHIGAR, Tiziano",1,1,2025,42,240,31/25,Legajos,1°1° 2025 Legajos.docx
1,"AGUILAR, Ian Nicolás",1,1,2025,42,241,32/25,Legajos,1°1° 2025 Legajos.docx
2,"ALTAMIRANO, Joaquin Román",1,1,2025,42,242,33/25,Legajos,1°1° 2025 Legajos.docx
3,"ARANDA, Maia Mariel",1,1,2025,42,243,34/25,Legajos,1°1° 2025 Legajos.docx
4,"CARRERAS FLAMMINI, Paula Sofía",1,1,2025,42,244,35/25,Legajos,1°1° 2025 Legajos.docx

#### Estandarización de nombres

In [68]:
df_datos["nombre_completo"] = df_datos["nombre_completo"].str.strip()
df_legajos["nombre_completo"] = df_legajos["nombre_completo"].str.strip()
df_marzo["nombre_completo"] = df_marzo["nombre_completo"].str.strip()

### 1.4 - Cruce de dataframes del curso 1°1° para validación de datos
Se realiza un cruzamiento manual de los dataframes base de las tres fuentes, pertenecientes al curso 1° división 1°, el cual determinará la consistencia de los datos, y dará paso al escalamiento automático de los 27 archivos restantes para cada fuente, antes de cruzarlos finalmente en la base de datos df_alumnos_master, la cual contará con la incorporación consecutiva de todos los alumnos de la institución, independiente del curso y división al que pertenezcan.

#### 1.4.1 - df_marzo vs df_legajos

**Objetivo del cruce:**
- ¿Tienen la misma cantidad de alumnos?
- ¿Tienen los mismos nombres?
- ¿Hay alguno en uno que no esté en el otro?

**Hipótesis:**
- Se espera una diferencia en el conteo de filas, debido a que df_legajos no cuenta con la alumna agregada con metadatos incrustados en df_marzo.

##### Paso 1 - Comparación de cantidades

In [69]:
len(df_marzo), len(df_legajos)

(28, 27)

##### Paso 2 - Crear conjuntos de nombres

In [70]:
nombres_marzo = set(df_marzo["nombre_completo"])
nombres_legajos = set(df_legajos["nombre_completo"])

##### Paso 3 - Nombres que están en un df y no en el otro

In [71]:
solo_en_marzo = nombres_marzo - nombres_legajos
solo_en_legajos = nombres_legajos - nombres_marzo

In [72]:
solo_en_marzo

{'MARTINEZ, Sofia Isabella'}

In [73]:
solo_en_legajos

set()

#### Insigts del cruce
**Validación de hipótesis**
- Efectivamente, la única diferencia la establece la alumna MARTINEZ, Sofía Isabella, quien supone un dato tardío por traslado desde otra institución con el ciclo lectivo en curso.

**Conclusiones:**
- datos consistentes
- limpieza de datos efectiva

#### 1.4.2 - df_datos vs df_legajos

**Objetivo del cruce:**
- ¿Tienen la misma cantidad de alumnos?
- ¿Tienen los mismos nombres?
- ¿Hay alguno en uno que no esté en el otro?
- ¿Coinciden los datos de las columnas [['libro_matriz','folio','legajo']]?

**Hipótesis:**
- No se esperan diferencias en el conteo de registros, debido a que los dos archivos fuente se confeccionaron antes del traslado de MARTINEZ, Sofia.

##### Paso 1 - Validación de nombres

In [74]:
nombres_datos = set(df_datos["nombre_completo"])
nombres_legajos = set(df_legajos["nombre_completo"])

##### Paso 2 - Merge (unión de tablas con columnas duplicadas separadas)

In [75]:
df_cruce = df_datos.merge(
    df_legajos,
    on="nombre_completo",
    how="inner",
    suffixes=("_datos","_legajos")
)

##### Paso 3 - Revisión de cantidad de registros

In [76]:
len(df_cruce)

27

##### Paso 4 - Detección de inconsistencias

In [77]:
df_cruce[
    (df_cruce["libro_matriz_datos"] != df_cruce["libro_matriz_legajos"]) | (df_cruce["folio_datos"] != df_cruce["folio_legajos"]) |
    (df_cruce["legajo_datos"] != df_cruce["legajo_legajos"])
    ]

Empty DataFrame
Columns: [nombre_completo, curso_datos, division_datos, anio_datos, libro_matriz_datos, folio_datos, legajo_datos, esc_proced, dni, fecha_nac, lugar_nac, edad, dirección, telefono_original, telefono_num, tipo_contacto, fuente_datos, archivo_origen_datos, curso_legajos, division_legajos, anio_legajos, libro_matriz_legajos, folio_legajos, legajo_legajos, fuente_legajos, archivo_origen_legajos]
Index: []

[0 rows x 26 columns]

#### Insigts del cruce
**Validación de hipótesis**
- Como se esperaba, según la hipótesis, no hay diferencias en cantidades de registros. Tampoco arroja diferencia por inconsistencia de datos.

**Conclusiones:**
- datos consistentes
- limpieza de datos efectiva

### 1.5 - Automatización por fuente 
#### Fuente: Datos (FP)