# Test manual — extractores.py y normalizacion.py

Notebook de laboratorio para probar funciones de extracción y normalización desde las fuentes declaradas.

Este notebook no forma parte del pipeline operativo.
Se usa únicamente para verificar comportamiento de funciones antes de integrarlas en otros módulos.

# Prueba de extractores.py para fuente Datos

In [1]:
import sys

sys.path.append(r"C:\ees2-school-database-pipeline")

In [2]:
from src.extractores import extraer_datos_raw

In [3]:
ruta = r"C:\ees2-school-database-pipeline\data\raw\datos\1°1° 2025 Datos.docx"

df_datos_raw = extraer_datos_raw(
    ruta_archivo=ruta,
    curso="1",
    division="1",
    anio="2025"
)

df_datos_raw.head()

,Nº,APELLIDO Y NOMBRES DEL ALUMNO,LM,F,Leg,ESC,D.N.I.,F.N.,Lugar,E,Dirección,Teléfono,curso,division,anio,fuente,archivo_origen
0,,"ACHIGAR, Tiziano",42,240,31/25,25,52746170,26/12/12,Punta Alta,12,Humberto 2538,2932-520752M,1,1,2025,datos,C:\ees2-school-database-pipeline\data\raw\dato...
1,,"AGUILAR, Ian Nicolás",42,241,32/25,4,52778569,27/11/12,Punta Alta,12,Bº Albatros XXVII c393,2932-573441M,1,1,2025,datos,C:\ees2-school-database-pipeline\data\raw\dato...
2,,"ALTAMIRANO, Joaquin Román",42,242,33/25,8,52887715,14/01/13,San Juan,12,Humberto 1916,2932-614538M,1,1,2025,datos,C:\ees2-school-database-pipeline\data\raw\dato...
3,,"ARANDA, Maia Mariel",42,243,34/25,1,52617713,06/07/12,Punta Alta,12,Entre Ríos 1899,2932-520048P,1,1,2025,datos,C:\ees2-school-database-pipeline\data\raw\dato...
4,,"CARRERAS FLAMMINI, Paula Sofía",42,244,35/25,8,52961006,01/02/13,Juris Fed,12,Humberto 2447,2932-505154M,1,1,2025,datos,C:\ees2-school-database-pipeline\data\raw\dato...

In [4]:
df_datos_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Nº                             27 non-null     str
 1   APELLIDO Y NOMBRES DEL ALUMNO  27 non-null     str
 2   LM                             27 non-null     str
 3   F                              27 non-null     str
 4   Leg                            27 non-null     str
 5   ESC                            27 non-null     str
 6   D.N.I.                         27 non-null     str
 7   F.N.                           27 non-null     str
 8   Lugar                          27 non-null     str
 9   E                              27 non-null     str
 10  Dirección                      27 non-null     str
 11  Teléfono                       27 non-null     str
 12  curso                          27 non-null     str
 13  division                       27 non-null     str
 14  anio                           27 non-null     str
 15  fuente                         27 non-null     str
 16  archivo_origen                 27 non-null     str
dtypes: str(17)
memory usage: 3.7 KB

In [5]:
df_datos_raw.tail()

,Nº,APELLIDO Y NOMBRES DEL ALUMNO,LM,F,Leg,ESC,D.N.I.,F.N.,Lugar,E,Dirección,Teléfono,curso,division,anio,fuente,archivo_origen
22,,"SANCHEZ PEÑA, Milagros Agostina",43,13,54/25,1,50467337,22/04/11,Juris Fed,14,Bº Albatros XXVII c160,2932-573334M,1,1,2025,datos,C:\ees2-school-database-pipeline\data\raw\dato...
23,,"UBEDA, Franco Lionel",43,14,55/25,25,48345434,11/07/10,Juris Fed,14,Humberto 3655,2932-509256M,1,1,2025,datos,C:\ees2-school-database-pipeline\data\raw\dato...
24,,"UÑATE, Thiago Santino",43,15,56/25,25,52961001,04/02/13,Juris Fed,12,Buchardo 3266,2932-631139M,1,1,2025,datos,C:\ees2-school-database-pipeline\data\raw\dato...
25,,"ZACARIAS, Kevin Alejandro",43,16,57/25,4,52617707,26/07/12,Punta Alta,12,17 de febrero 1794,2932-457126M,1,1,2025,datos,C:\ees2-school-database-pipeline\data\raw\dato...
26,,"ZERPA, Fernando Damián",43,17,58/25,16,52710252,13/09/12,Bs As,12,Río Colorado 210,2932-476473P,1,1,2025,datos,C:\ees2-school-database-pipeline\data\raw\dato...

In [6]:
df_datos_raw.columns

Index(['Nº', 'APELLIDO Y NOMBRES DEL ALUMNO', 'LM', 'F', 'Leg', 'ESC',
       'D.N.I.', 'F.N.', 'Lugar', 'E', 'Dirección', 'Teléfono', 'curso',
       'division', 'anio', 'fuente', 'archivo_origen'],
      dtype='str')

In [7]:
df_datos_raw.shape

(27, 17)

# Prueba de extractores.py para fuente Legajos

In [8]:
from src.extractores import extraer_legajos_raw

In [9]:
ruta_legajos = r"C:\ees2-school-database-pipeline\data\raw\legajos\1°1° 2025 Legajos.docx"

df_legajos_raw = extraer_legajos_raw(
    ruta_archivo=ruta_legajos,
    curso="1",
    division="1",
    anio="2025"
)

In [10]:
df_legajos_raw.shape

(27, 10)

In [11]:
df_legajos_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Nº                             27 non-null     str
 1   APELLIDO Y NOMBRES DEL ALUMNO  27 non-null     str
 2   LM                             27 non-null     str
 3   F                              27 non-null     str
 4   Leg                            27 non-null     str
 5   curso                          27 non-null     str
 6   division                       27 non-null     str
 7   anio                           27 non-null     str
 8   fuente                         27 non-null     str
 9   archivo_origen                 27 non-null     str
dtypes: str(10)
memory usage: 2.2 KB

In [12]:
df_legajos_raw.head()

,Nº,APELLIDO Y NOMBRES DEL ALUMNO,LM,F,Leg,curso,division,anio,fuente,archivo_origen
0,,"ACHIGAR, Tiziano",42,240,31/25,1,1,2025,legajos,C:\ees2-school-database-pipeline\data\raw\lega...
1,,"AGUILAR, Ian Nicolás",42,241,32/25,1,1,2025,legajos,C:\ees2-school-database-pipeline\data\raw\lega...
2,,"ALTAMIRANO, Joaquin Román",42,242,33/25,1,1,2025,legajos,C:\ees2-school-database-pipeline\data\raw\lega...
3,,"ARANDA, Maia Mariel",42,243,34/25,1,1,2025,legajos,C:\ees2-school-database-pipeline\data\raw\lega...
4,,"CARRERAS FLAMMINI, Paula Sofía",42,244,35/25,1,1,2025,legajos,C:\ees2-school-database-pipeline\data\raw\lega...

In [13]:
df_legajos_raw.tail()

,Nº,APELLIDO Y NOMBRES DEL ALUMNO,LM,F,Leg,curso,division,anio,fuente,archivo_origen
22,,"SANCHEZ PEÑA, Milagros Agostina",43,13,54/25,1,1,2025,legajos,C:\ees2-school-database-pipeline\data\raw\lega...
23,,"UBEDA, Franco Lionel",43,14,55/25,1,1,2025,legajos,C:\ees2-school-database-pipeline\data\raw\lega...
24,,"UÑATE, Thiago Santino",43,15,56/25,1,1,2025,legajos,C:\ees2-school-database-pipeline\data\raw\lega...
25,,"ZACARIAS, Kevin Alejandro",43,16,57/25,1,1,2025,legajos,C:\ees2-school-database-pipeline\data\raw\lega...
26,,"ZERPA, Fernando Damián",43,17,58/25,1,1,2025,legajos,C:\ees2-school-database-pipeline\data\raw\lega...

# Prueba de extractores.py para fuente Marzo

In [14]:
from src.extractores import extraer_marzo_raw

In [15]:
ruta_marzo = r"C:\ees2-school-database-pipeline\data\raw\marzo\1°1° 2025 Marzo.docx"

df_marzo_raw = extraer_marzo_raw(
    ruta_archivo=ruta_marzo,
    curso="1",
    division="1",
    anio="2025"
)

In [16]:
df_marzo_raw.shape

(28, 7)

In [17]:
df_marzo_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Nº                             28 non-null     str
 1   APELLIDO Y NOMBRES DEL ALUMNO  28 non-null     str
 2   curso                          28 non-null     str
 3   division                       28 non-null     str
 4   anio                           28 non-null     str
 5   fuente                         28 non-null     str
 6   archivo_origen                 28 non-null     str
dtypes: str(7)
memory usage: 1.7 KB

In [18]:
df_marzo_raw.head()

,Nº,APELLIDO Y NOMBRES DEL ALUMNO,curso,division,anio,fuente,archivo_origen
0,,"ACHIGAR, Tiziano",1,1,2025,marzo,C:\ees2-school-database-pipeline\data\raw\marz...
1,,"AGUILAR, Ian Nicolás",1,1,2025,marzo,C:\ees2-school-database-pipeline\data\raw\marz...
2,,"ALTAMIRANO, Joaquin Román",1,1,2025,marzo,C:\ees2-school-database-pipeline\data\raw\marz...
3,,"ARANDA, Maia Mariel",1,1,2025,marzo,C:\ees2-school-database-pipeline\data\raw\marz...
4,,"CARRERAS FLAMMINI, Paula Sofía",1,1,2025,marzo,C:\ees2-school-database-pipeline\data\raw\marz...

# Prueba de normalizacion.py para fuente Datos

In [19]:
from src.normalizacion import normalizar_datos

In [20]:
df_datos_stg = normalizar_datos(df_datos_raw)

In [21]:
df_datos_stg.shape

(27, 29)

In [22]:
df_datos_stg.info()

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   numero_raw               27 non-null     str
 1   nombre_original          27 non-null     str
 2   libro_matriz_raw         27 non-null     str
 3   folio_raw                27 non-null     str
 4   legajo_raw               27 non-null     str
 5   escuela_procedencia_raw  27 non-null     str
 6   dni_raw                  27 non-null     str
 7   fecha_nacimiento_raw     27 non-null     str
 8   lugar_nacimiento_raw     27 non-null     str
 9   edad_raw                 27 non-null     str
 10  direccion_raw            27 non-null     str
 11  telefono_raw             27 non-null     str
 12  curso                    27 non-null     str
 13  division                 27 non-null     str
 14  anio                     27 non-null     str
 15  fuente                   27 non-null     str
 16  archivo_origen           27 non-null     str
 17  nombre_completo          27 non-null     str
 18  libro_matriz             27 non-null     str
 19  folio                    27 non-null     str
 20  legajo                   27 non-null     str
 21  escuela_procedencia      27 non-null     str
 22  dni                      27 non-null     str
 23  fecha_nacimiento         27 non-null     str
 24  lugar_nacimiento         27 non-null     str
 25  edad                     27 non-null     str
 26  direccion                27 non-null     str
 27  telefono_num             27 non-null     str
 28  tipo_contacto            26 non-null     str
dtypes: str(29)
memory usage: 6.2 KB

In [23]:
df_datos_stg.head()

,numero_raw,nombre_original,libro_matriz_raw,folio_raw,legajo_raw,escuela_procedencia_raw,dni_raw,fecha_nacimiento_raw,lugar_nacimiento_raw,edad_raw,...,folio,legajo,escuela_procedencia,dni,fecha_nacimiento,lugar_nacimiento,edad,direccion,telefono_num,tipo_contacto
0,,"ACHIGAR, Tiziano",42,240,31/25,25,52746170,26/12/12,Punta Alta,12,...,240,31/25,25,52746170,26/12/12,Punta Alta,12,Humberto 2538,2932-520752,M
1,,"AGUILAR, Ian Nicolás",42,241,32/25,4,52778569,27/11/12,Punta Alta,12,...,241,32/25,4,52778569,27/11/12,Punta Alta,12,Bº Albatros XXVII c393,2932-573441,M
2,,"ALTAMIRANO, Joaquin Román",42,242,33/25,8,52887715,14/01/13,San Juan,12,...,242,33/25,8,52887715,14/01/13,San Juan,12,Humberto 1916,2932-614538,M
3,,"ARANDA, Maia Mariel",42,243,34/25,1,52617713,06/07/12,Punta Alta,12,...,243,34/25,1,52617713,06/07/12,Punta Alta,12,Entre Ríos 1899,2932-520048,P
4,,"CARRERAS FLAMMINI, Paula Sofía",42,244,35/25,8,52961006,01/02/13,Juris Fed,12,...,244,35/25,8,52961006,01/02/13,Juris Fed,12,Humberto 2447,2932-505154,M

In [24]:
df_datos_stg.columns.tolist()

['numero_raw',
 'nombre_original',
 'libro_matriz_raw',
 'folio_raw',
 'legajo_raw',
 'escuela_procedencia_raw',
 'dni_raw',
 'fecha_nacimiento_raw',
 'lugar_nacimiento_raw',
 'edad_raw',
 'direccion_raw',
 'telefono_raw',
 'curso',
 'division',
 'anio',
 'fuente',
 'archivo_origen',
 'nombre_completo',
 'libro_matriz',
 'folio',
 'legajo',
 'escuela_procedencia',
 'dni',
 'fecha_nacimiento',
 'lugar_nacimiento',
 'edad',
 'direccion',
 'telefono_num',
 'tipo_contacto']

# Prueba de normalizacion.py para fuente Legajos

In [25]:
from src.normalizacion import normalizar_legajos

In [26]:
df_legajos_stg = normalizar_legajos(df_legajos_raw)

In [27]:
df_legajos_stg.shape

(27, 14)

In [28]:
df_legajos_stg.info()

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   numero_raw        27 non-null     str
 1   nombre_original   27 non-null     str
 2   libro_matriz_raw  27 non-null     str
 3   folio_raw         27 non-null     str
 4   legajo_raw        27 non-null     str
 5   curso             27 non-null     str
 6   division          27 non-null     str
 7   anio              27 non-null     str
 8   fuente            27 non-null     str
 9   archivo_origen    27 non-null     str
 10  nombre_completo   27 non-null     str
 11  libro_matriz      27 non-null     str
 12  folio             27 non-null     str
 13  legajo            27 non-null     str
dtypes: str(14)
memory usage: 3.1 KB

In [29]:
df_legajos_stg.head()

,numero_raw,nombre_original,libro_matriz_raw,folio_raw,legajo_raw,curso,division,anio,fuente,archivo_origen,nombre_completo,libro_matriz,folio,legajo
0,,"ACHIGAR, Tiziano",42,240,31/25,1,1,2025,legajos,C:\ees2-school-database-pipeline\data\raw\lega...,"ACHIGAR, Tiziano",42,240,31/25
1,,"AGUILAR, Ian Nicolás",42,241,32/25,1,1,2025,legajos,C:\ees2-school-database-pipeline\data\raw\lega...,"AGUILAR, Ian Nicolás",42,241,32/25
2,,"ALTAMIRANO, Joaquin Román",42,242,33/25,1,1,2025,legajos,C:\ees2-school-database-pipeline\data\raw\lega...,"ALTAMIRANO, Joaquin Román",42,242,33/25
3,,"ARANDA, Maia Mariel",42,243,34/25,1,1,2025,legajos,C:\ees2-school-database-pipeline\data\raw\lega...,"ARANDA, Maia Mariel",42,243,34/25
4,,"CARRERAS FLAMMINI, Paula Sofía",42,244,35/25,1,1,2025,legajos,C:\ees2-school-database-pipeline\data\raw\lega...,"CARRERAS FLAMMINI, Paula Sofía",42,244,35/25

In [30]:
df_legajos_stg.columns.tolist()

['numero_raw',
 'nombre_original',
 'libro_matriz_raw',
 'folio_raw',
 'legajo_raw',
 'curso',
 'division',
 'anio',
 'fuente',
 'archivo_origen',
 'nombre_completo',
 'libro_matriz',
 'folio',
 'legajo']

# Prueba de normalizacion.py para fuente Marzo

In [31]:
from src.normalizacion import normalizar_marzo

In [32]:
df_marzo_stg = normalizar_marzo(df_marzo_raw)

In [33]:
df_marzo_stg.shape

(28, 11)

In [34]:
df_marzo_stg.info()

<class 'pandas.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   numero_raw            28 non-null     str
 1   nombre_original       28 non-null     str
 2   curso                 28 non-null     str
 3   division              28 non-null     str
 4   anio                  28 non-null     str
 5   fuente                28 non-null     str
 6   archivo_origen        28 non-null     str
 7   nombre_completo       28 non-null     str
 8   observacion_marzo     0 non-null      object
 9   tipo_evento_inferido  28 non-null     str
 10  requiere_revision     28 non-null     bool
dtypes: bool(1), object(1), str(9)
memory usage: 2.3+ KB

In [35]:
df_marzo_stg.head()

,numero_raw,nombre_original,curso,division,anio,fuente,archivo_origen,nombre_completo,observacion_marzo,tipo_evento_inferido,requiere_revision
0,,"ACHIGAR, Tiziano",1,1,2025,marzo,C:\ees2-school-database-pipeline\data\raw\marz...,"ACHIGAR, Tiziano",None,presencia_simple,False
1,,"AGUILAR, Ian Nicolás",1,1,2025,marzo,C:\ees2-school-database-pipeline\data\raw\marz...,"AGUILAR, Ian Nicolás",None,presencia_simple,False
2,,"ALTAMIRANO, Joaquin Román",1,1,2025,marzo,C:\ees2-school-database-pipeline\data\raw\marz...,"ALTAMIRANO, Joaquin Román",None,presencia_simple,False
3,,"ARANDA, Maia Mariel",1,1,2025,marzo,C:\ees2-school-database-pipeline\data\raw\marz...,"ARANDA, Maia Mariel",None,presencia_simple,False
4,,"CARRERAS FLAMMINI, Paula Sofía",1,1,2025,marzo,C:\ees2-school-database-pipeline\data\raw\marz...,"CARRERAS FLAMMINI, Paula Sofía",None,presencia_simple,False

In [36]:
df_marzo_stg.columns.tolist()

['numero_raw',
 'nombre_original',
 'curso',
 'division',
 'anio',
 'fuente',
 'archivo_origen',
 'nombre_completo',
 'observacion_marzo',
 'tipo_evento_inferido',
 'requiere_revision']